### PR TITLE
 add support for synced_block.

### PR DESCRIPTION
**Pull request by Doradx**
fix the bug when querying children blocks for synced_block.

### CODE REVIEW

**Comment by souvikinator** [comment]
Can you elaborate on the bug you encountered?

**Comment by Doradx** [comment]
When I use the original code, it can't get the child block of synced_block.
Because the child block can't be queried with the ID of the parent block, what I found when I debug with notion API, it should be queried with synced_block.synced_from.block_id.

**Comment by souvikinator** [comment]
So the content of the `synced_block` is not getting rendered right? If that is the case then, it works fine on my end:

This is the parent page with a synced block and the child page (Page-1) includes the same synced block.
image

output:
image

if this is not the issue then please provide steps to reproduce the bug.

**Comment by Doradx** [comment]
It works fine for the referenced page (page A) but not for the slave page (page B) refers to page A.
For example, when you write something on page A, then copy and sync it to page B, the exported markdown files only work fine for page A, not page B.
You can find the reason in the response from notion API.
Response from Notion, for page A
Response from Notion, for page B
the UUID of the block is `d87824d6-b706-4a1e-b060-878b0c2909b5`, and it appeared as the block id for page A, but as `synced_block.synced_from.block_id` for page B. And the output of sycned_block for page B will be empty if you query its content without using `synced_block.synced_from.block_id`.

**Comment by souvikinator** [comment]
Thanks for explaining. That makes it clear. I'll merge it and it should be live in the upcoming update. Thank you for your contribution.

**Review by souvikinator — APPROVED** [review]

**Pull request merged**
