### PR TITLE
feat: add numbers to ordered list item

### LINKED ISSUE #18: Incorrect syntax for the orderest lists.
Hey,
 For the ordered lists (numbered_list_item) , the incorrect syntax for unordered lists (bulleted_list_item) is rendered.

Expected:
```md
1. Hey
2. There
```

Actual:
```md
- Hey
- There
```

I have tried an approach that might be able to solve this issue #19. Happy to discuss on it.

### PR DESCRIPTION
**Pull request by ShubhamVerma1811**
This PR aims to fix #18 .

I have a created a class variable that would act as counter for ordered list.
The implementation of this is open for discussion.

It does not support nested <ol/> with numbers like
```md
1. A
2. B
  a.  Sub B
```

### CODE REVIEW

**Comment by souvikinator** [comment]
Hey, thanks for the contribution. 
Works as expected however as you mentioned it doesn't support nested lists.
The current implementation uses a counter, I guess we can accomplish the nested numbering recursively.

**Comment by souvikinator** [comment]
Probably by adding a new argument to `blocksToMarkdown`. If a block has nesting then we can pass a new instance of the counter with the initial value `1`  to `blocksToMarkdown` and it gets incremented. I'll share an example snippet shortly to make things clear.

**Comment by ShubhamVerma1811** [comment]
Right, I got the gist of what you are saying..
Let me try something along those lines.

**Comment by souvikinator** [comment]
Fixed in #38

**Pull request closed without merging**
