### PR TITLE
feat: add setCustomTransformer. Customize parsing!

### PR DESCRIPTION
**Pull request by froger**
* add n2m.setCustomTransformer(string, function)
* short-cut parsing when a custom transformer is set

### CODE REVIEW

**Comment by froger** [comment]
Hello @souvikinator !
Thanks for this repo, it's really helpful. While developing scripts to transform notion pages to Docusaurus markdown, I've stumbled on a specific need that may help other: I want to be able to change some parsing in a very "docusaurus" way, like handling the embed betters. 

So here what I've done: 

```
n2m.setCustomTransformer('embed', async (block) => {
  const {embed} = block as any;
  if (!embed?.url) return '';
  return `<figure>
<iframe style={{border: "none"}} width="800" height="450" src="${
    embed?.url
  }"></iframe>
<figcaption>${await n2m.blockToMarkdown(embed?.caption)}</figcaption>
</figure>`;
});
```

This way, when the parser have a "embed" type, it executes this function and not the default one. It can fits any other type. 

Tradeoffs: The types for `ListBlockChildrenResponseResult` have not all the notion types, so it may be needed to do a `any` type-casting.

**Comment by souvikinator** [comment]
Hello there,
Thanks for the contribution. That definitely is a useful feature. 

I'll test it locally and create a new release shortly.

**Comment by souvikinator** [comment]
Wow that's a pretty awesome feature. Just love it 💯.
It's live in `v2.5.0`.

**Comment by souvikinator** [comment]
Hi again! Your past feedback on notion-to-md has been valuable. 

We're now working on **v4** with major improvements to address various use cases better.  **V4** extends on this and takes it way beyond Markdown.

 I'd love your insights on this. Please checkout the GitHub discussion #112   to discuss or share your feedback? Your feedback would be really valuable in shaping v4's development.

**Pull request merged**
